-- =====================================================================
-- V1__baseline_schema.sql  —  Flyway baseline (ceid-timetabling-system)
--
-- Αποτυπώνει ΑΥΤΟΥΣΙΟ το υπάρχον σχήμα (όπως το είχε παραγάγει το Hibernate
-- με ddl-auto=update), εξαγμένο μέσω
--   pg_dump --schema-only --no-owner --no-privileges
-- και καθαρισμένο από psql meta-commands (\restrict) + session SET ώστε να
-- εκτελείται από το Flyway μέσω JDBC.
--
-- Από εδώ και πέρα (κανόνας CLAUDE.md #5): ΚΑΘΕ αλλαγή σχήματος = ΝΕΟ versioned
-- migration (Vx__desc.sql). ΠΟΤΕ μην επεξεργάζεσαι αυτό το αρχείο.
--
-- Συμπεριφορά:
--   * Υπάρχουσες (μη-κενές) βάσεις -> baseline-on-migrate κάνει baseline στην
--     έκδοση 1 και ΔΕΝ εκτελεί αυτό το script (το σχήμα υπάρχει ήδη).
--   * Κενές βάσεις (CI/καθαρό dev) -> το script εκτελείται και χτίζει το σχήμα.
-- =====================================================================

-- ---------------------------------------------------------------------
-- Tables (+ identity sequences)
-- ---------------------------------------------------------------------

CREATE TABLE public.course_teachers (
    id bigint NOT NULL,
    role character varying(255) NOT NULL,
    course_id bigint NOT NULL,
    teacher_id bigint NOT NULL,
    CONSTRAINT course_teachers_role_check CHECK (((role)::text = ANY ((ARRAY['PRIMARY'::character varying, 'SECONDARY'::character varying, 'LAB_INSTRUCTOR'::character varying, 'TUTORIAL_INSTRUCTOR'::character varying])::text[])))
);

ALTER TABLE public.course_teachers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.course_teachers_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.courses (
    active boolean NOT NULL,
    ects integer,
    exam_duration_minutes integer,
    expected_students integer,
    lab_hours integer,
    lecture_hours integer,
    needs_lab boolean,
    needs_projector boolean,
    semester integer NOT NULL,
    study_year integer NOT NULL,
    tutorial_hours integer,
    visible_in_timetable boolean NOT NULL,
    id bigint NOT NULL,
    sector character varying(10),
    code character varying(30) NOT NULL,
    name character varying(200) NOT NULL,
    teachers_text character varying(500),
    course_type character varying(255) NOT NULL,
    notes text,
    semester_type character varying(255) NOT NULL,
    preferred_exam_hours character varying(50),
    preferred_exam_rooms character varying(200),
    CONSTRAINT courses_course_type_check CHECK (((course_type)::text = ANY ((ARRAY['REQUIRED'::character varying, 'REQUIRED_ELECTIVE'::character varying, 'GENERAL_EDUCATION'::character varying, 'EXTERNAL'::character varying])::text[]))),
    CONSTRAINT courses_semester_type_check CHECK (((semester_type)::text = ANY ((ARRAY['FALL'::character varying, 'SPRING'::character varying, 'BOTH'::character varying])::text[])))
);

ALTER TABLE public.courses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.courses_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.room_constraints (
    id bigint NOT NULL,
    constraint_type character varying(255) NOT NULL,
    day_of_week character varying(255) NOT NULL,
    hour integer NOT NULL,
    room_id bigint NOT NULL,
    CONSTRAINT room_constraints_constraint_type_check CHECK (((constraint_type)::text = 'BLOCKED'::text))
);

ALTER TABLE public.room_constraints ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.room_constraints_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.rooms (
    available_for_exams boolean,
    available_for_semester boolean,
    capacity integer NOT NULL,
    has_computers boolean,
    has_projector boolean,
    id bigint NOT NULL,
    code character varying(20) NOT NULL,
    name character varying(100) NOT NULL,
    notes text,
    room_type character varying(255) NOT NULL,
    CONSTRAINT rooms_room_type_check CHECK (((room_type)::text = ANY ((ARRAY['AMPHITHEATER'::character varying, 'CLASSROOM'::character varying, 'LAB'::character varying, 'MEETING_ROOM'::character varying, 'EXAM_HALL'::character varying])::text[])))
);

ALTER TABLE public.rooms ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rooms_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.teacher_constraints (
    id bigint NOT NULL,
    constraint_type character varying(255) NOT NULL,
    day_of_week character varying(255) NOT NULL,
    hour integer NOT NULL,
    teacher_id bigint NOT NULL,
    CONSTRAINT teacher_constraints_constraint_type_check CHECK (((constraint_type)::text = ANY ((ARRAY['BLOCKED'::character varying, 'PREFERRED'::character varying])::text[])))
);

ALTER TABLE public.teacher_constraints ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.teacher_constraints_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.teachers (
    id bigint NOT NULL,
    department character varying(255),
    email character varying(255),
    name character varying(255) NOT NULL,
    notes character varying(255),
    short_name character varying(255),
    teacher_type character varying(255),
    CONSTRAINT teachers_teacher_type_check CHECK (((teacher_type)::text = ANY ((ARRAY['PROFESSOR'::character varying, 'ASSOCIATE_PROFESSOR'::character varying, 'ASSISTANT_PROFESSOR'::character varying, 'LECTURER'::character varying, 'EDIP'::character varying, 'ETEP'::character varying, 'EXTERNAL'::character varying, 'APPOINTED'::character varying])::text[])))
);

ALTER TABLE public.teachers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.teachers_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.time_slots (
    end_time time(6) without time zone NOT NULL,
    specific_date date,
    start_time time(6) without time zone NOT NULL,
    id bigint NOT NULL,
    exam_period_label character varying(50),
    day_of_week character varying(255) NOT NULL,
    slot_type character varying(255) NOT NULL,
    CONSTRAINT time_slots_day_of_week_check CHECK (((day_of_week)::text = ANY ((ARRAY['MONDAY'::character varying, 'TUESDAY'::character varying, 'WEDNESDAY'::character varying, 'THURSDAY'::character varying, 'FRIDAY'::character varying, 'SATURDAY'::character varying, 'SUNDAY'::character varying])::text[]))),
    CONSTRAINT time_slots_slot_type_check CHECK (((slot_type)::text = ANY ((ARRAY['SEMESTER'::character varying, 'EXAM'::character varying])::text[])))
);

ALTER TABLE public.time_slots ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.time_slots_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.timetable_assignments (
    is_locked boolean,
    manually_assigned boolean,
    course_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    room_id bigint NOT NULL,
    time_slot_id bigint NOT NULL,
    timetable_id bigint NOT NULL,
    assignment_type character varying(255) NOT NULL,
    exam_duration_minutes integer,
    CONSTRAINT timetable_assignments_assignment_type_check CHECK (((assignment_type)::text = ANY ((ARRAY['LECTURE'::character varying, 'TUTORIAL'::character varying, 'LAB'::character varying, 'EXAM'::character varying])::text[])))
);

ALTER TABLE public.timetable_assignments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.timetable_assignments_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.timetable_excluded_dates (
    timetable_id bigint NOT NULL,
    excluded_date date
);

CREATE TABLE public.timetables (
    end_date date,
    solver_conflicts integer,
    solver_score double precision,
    solver_time_seconds integer,
    start_date date,
    created_at timestamp(6) without time zone,
    created_by bigint,
    id bigint NOT NULL,
    published_at timestamp(6) without time zone,
    academic_year character varying(10) NOT NULL,
    name character varying(200) NOT NULL,
    notes text,
    semester_type character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    timetable_type character varying(255) NOT NULL,
    CONSTRAINT timetables_semester_type_check CHECK (((semester_type)::text = ANY ((ARRAY['FALL'::character varying, 'SPRING'::character varying, 'SEPTEMBER'::character varying])::text[]))),
    CONSTRAINT timetables_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'SOLVING'::character varying, 'SOLVED'::character varying, 'PUBLISHED'::character varying])::text[]))),
    CONSTRAINT timetables_timetable_type_check CHECK (((timetable_type)::text = ANY ((ARRAY['SEMESTER'::character varying, 'EXAM'::character varying])::text[])))
);

ALTER TABLE public.timetables ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.timetables_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.users (
    active boolean NOT NULL,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    sector character varying(10),
    username character varying(50) NOT NULL,
    email character varying(100),
    full_name character varying(150) NOT NULL,
    password_hash character varying(255),
    role character varying(255) NOT NULL,
    teacher_id bigint,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'TEACHER'::character varying, 'STUDENT'::character varying])::text[])))
);

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

-- ---------------------------------------------------------------------
-- Primary keys & unique constraints
-- ---------------------------------------------------------------------

ALTER TABLE ONLY public.course_teachers
    ADD CONSTRAINT course_teachers_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT courses_code_key UNIQUE (code);

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT courses_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.room_constraints
    ADD CONSTRAINT room_constraints_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.rooms
    ADD CONSTRAINT rooms_code_key UNIQUE (code);

ALTER TABLE ONLY public.rooms
    ADD CONSTRAINT rooms_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.teacher_constraints
    ADD CONSTRAINT teacher_constraints_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.teachers
    ADD CONSTRAINT teachers_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.time_slots
    ADD CONSTRAINT time_slots_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.timetable_assignments
    ADD CONSTRAINT timetable_assignments_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.timetables
    ADD CONSTRAINT timetables_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.course_teachers
    ADD CONSTRAINT uk8o1ukkoyj5rwp1nb680sk8ju7 UNIQUE (course_id, teacher_id, role);

ALTER TABLE ONLY public.teachers
    ADD CONSTRAINT ukjopvho0c55q6qp655fnpbughx UNIQUE (short_name);

ALTER TABLE ONLY public.room_constraints
    ADD CONSTRAINT ukmpwojrp34b0iligmf42xkhpmt UNIQUE (room_id, day_of_week, hour);

ALTER TABLE ONLY public.teacher_constraints
    ADD CONSTRAINT ukpcq1aolap9hxp9ixlp5qooy6 UNIQUE (teacher_id, day_of_week, hour);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);

-- ---------------------------------------------------------------------
-- Foreign keys
-- ---------------------------------------------------------------------

ALTER TABLE ONLY public.timetable_assignments
    ADD CONSTRAINT fk1dcyktgr591o5xme2ige73vni FOREIGN KEY (course_id) REFERENCES public.courses(id);

ALTER TABLE ONLY public.timetable_assignments
    ADD CONSTRAINT fk5nty15gadf1q3hetvt4awkaka FOREIGN KEY (timetable_id) REFERENCES public.timetables(id);

ALTER TABLE ONLY public.course_teachers
    ADD CONSTRAINT fk84v77efghiwpxgicxggm5rpdv FOREIGN KEY (course_id) REFERENCES public.courses(id);

ALTER TABLE ONLY public.timetables
    ADD CONSTRAINT fk8xaogqbbdaenyqsst4tyxf67w FOREIGN KEY (created_by) REFERENCES public.users(id);

ALTER TABLE ONLY public.timetable_excluded_dates
    ADD CONSTRAINT fk9ql6qcslg0o9s1idhlt5a5aut FOREIGN KEY (timetable_id) REFERENCES public.timetables(id);

ALTER TABLE ONLY public.room_constraints
    ADD CONSTRAINT fk9wtcpsan0gfa3ltn6j891cj67 FOREIGN KEY (room_id) REFERENCES public.rooms(id);

ALTER TABLE ONLY public.timetable_assignments
    ADD CONSTRAINT fkfpd0ii29ywk80qgypofwaaare FOREIGN KEY (time_slot_id) REFERENCES public.time_slots(id);

ALTER TABLE ONLY public.course_teachers
    ADD CONSTRAINT fkrjd6pmvgpu5j7qoqo72cdo80s FOREIGN KEY (teacher_id) REFERENCES public.teachers(id);

ALTER TABLE ONLY public.timetable_assignments
    ADD CONSTRAINT fkrp7awe15ejgbde4kx6kbd4me6 FOREIGN KEY (room_id) REFERENCES public.rooms(id);

ALTER TABLE ONLY public.teacher_constraints
    ADD CONSTRAINT fkvad98252jbjggq4moarax7l3 FOREIGN KEY (teacher_id) REFERENCES public.teachers(id);
