-- =====================================================================
-- V4__add_constraint_weight_config.sql  —  editable constraint weights (S4b-2a)
--
-- Persistence layer για τα βάρη των solver constraints. Ένα row ανά κανόνα·
-- το constraint_key ταιριάζει 1-1 με τα keys του SolverWeights. Το seed των 31
-- κανόνων γίνεται σε Java (ConstraintWeightSeeder, insert-if-absent) — ΟΧΙ εδώ,
-- ίδιο idiom με V3/SnapshotBackfillRunner (single source = το SolverWeights
-- catalog· admin edits ΔΕΝ χάνονται σε restart).
--
-- Additive & μη-καταστροφικό: ΝΕΟΣ πίνακας μόνο, καμία αλλαγή σε υπάρχοντες,
-- ΚΑΝΕΝΑ data INSERT. ΠΡΟΣΟΧΗ (S4b-2a): ο solver ΔΕΝ διαβάζει ακόμα από εδώ —
-- το overlay στα live βάρη έρχεται στο S4b-2b (το loadConstraintsFromDb μένει
-- αμετάβλητο).
-- =====================================================================

CREATE TABLE public.constraint_weight_config (
    id             bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    constraint_key varchar(80)   NOT NULL,
    scope          varchar(10),
    score_level    varchar(4),
    weight         integer       NOT NULL,
    enabled        boolean       NOT NULL DEFAULT true,
    display_name   varchar(120),
    description    text,
    params         jsonb,
    created_at     timestamptz   NOT NULL DEFAULT now(),
    updated_at     timestamptz   NOT NULL DEFAULT now(),
    CONSTRAINT uq_constraint_weight_config_key UNIQUE (constraint_key)
);
