-- =====================================================================
-- V6__add_timetable_scoped_courses.sql — per-timetable frozen course scope (#5)
--
-- Immutability invariant #1 (επέκταση S3): το S3 πάγωσε display πεδία ΑΝΑ
-- ΑΝΑΘΕΣΗ· το #5 παγώνει «ποια μαθήματα ΑΝΗΚΟΥΝ» ΑΝΑ ΠΡΟΓΡΑΜΜΑ. Χωρίς αυτό, το
-- completeness (validateTimetableReport + getProgress) διάβαζε τον ΖΩΝΤΑΝΟ
-- κατάλογο (courseRepo.findAll()) → νέα/διαγραμμένα/edited μαθήματα διέρρεαν
-- αναδρομικά σε ΟΛΑ τα προγράμματα ως phantom MISSING_HOURS/MISSING_EXAM και
-- αλλοιωμένο completion %.
--
-- Κάθε γραμμή = ένα μάθημα εντός scope ενός προγράμματος, με ΠΑΓΩΜΕΝΑ τα πεδία
-- που χρειάζεται το completeness (code/name/εξάμηνο/έτος/τύπος + req ώρες ανά
-- τύπο + needs_exam). Το completeness διαβάζει ΑΥΤΟΝ τον πίνακα → άνοσο σε
-- προσθήκες/διαγραφές/edits μετά τη δημιουργία.
--
-- course_id ΧΩΡΙΣ foreign key (σκόπιμα): το scope ΠΡΕΠΕΙ να επιβιώνει hard
-- delete μαθήματος. Τα snapshot πεδία το κάνουν αυτάρκες. FK μόνο στο
-- timetable_id (ON DELETE CASCADE όταν σβήνει πρόγραμμα).
--
-- Additive & μη-καταστροφικό: DDL-only, ΚΑΝΕΝΑ data UPDATE. Backfill υπαρχόντων
-- προγραμμάτων σε Java (TimetableScopeBackfillRunner), idempotent.
-- =====================================================================

CREATE TABLE public.timetable_scoped_courses (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timetable_id          bigint  NOT NULL,
    course_id             bigint  NOT NULL,
    snapshot_course_code  varchar(30),
    snapshot_course_name  varchar(200),
    snapshot_semester     integer,
    snapshot_study_year   integer,
    snapshot_course_type  varchar(30),
    req_lecture_hours     integer NOT NULL DEFAULT 0,
    req_tutorial_hours    integer NOT NULL DEFAULT 0,
    req_lab_hours         integer NOT NULL DEFAULT 0,
    needs_exam            boolean NOT NULL DEFAULT true,
    created_at            timestamp(6) without time zone,
    CONSTRAINT uq_timetable_scoped_course UNIQUE (timetable_id, course_id),
    CONSTRAINT fk_scoped_timetable FOREIGN KEY (timetable_id)
        REFERENCES public.timetables(id) ON DELETE CASCADE
);

CREATE INDEX idx_scoped_timetable ON public.timetable_scoped_courses (timetable_id);
